# version format
version: 1.0.{build}-{branch}

os: Visual Studio 2015

platform: 
  - x64

environment:
  QTDIR: C:\Qt\5.6\msvc2015_64
  matrix:
    - XPIKS_BINARY: true
    - XPIKS_TESTS: true


branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

skip_commits:
  message: /.*\[skip\]/       # Regex for matching commit message

# clone directory
clone_folder: c:\projects\xpiks

# set clone depth
clone_depth: 3                      # clone entire repository history if not defined

# environment variables
# environment:
#  my_var1: value1
#  my_var2: value2

matrix:
  fast_finish: true
  
install:
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - git clone --depth=3 https://bitbucket.org/ribtoks/xpiks-deps.git c:\projects\xpiks-deps
  - cmd: 'cd c:\projects\xpiks-deps'
  - cmd: 'cd c:\projects\xpiks'
  - git submodule update --init --recursive
  - cmd: set QT_FATAL_WARNINGS=true
  - cmd: set PATH=%PATH%;%QTDIR%\bin
  - qmake -v

before_build:
  - cmd: 'xcopy /s c:\projects\xpiks-deps\windows-libs\debug-x64 c:\projects\xpiks\src\libs'
  - cmd: 'move c:\projects\xpiks-deps\hunspell-1.3.3 c:\projects\xpiks\src'
  - cmd: 'move c:\projects\xpiks-deps\zlib-1.2.8 c:\projects\xpiks\src'
  - cmd: 'cd c:\projects\xpiks'
  - cmd: 'ren src\tiny-aes\aes.c aes.cpp'
  - cmd: 'copy src\libs\mman.* src\cpp-libface\libs'
  - cmd: 'call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%'
  
build_script:
  - cmd: 'cd src'
  - cmd: 'cd quazip/quazip'
  - qmake "CONFIG+=debug" quazip.pro
  - nmake.exe
  - cmd: 'copy debug\quazip.lib ..\..\libs'
  - cmd: 'cd ..\..'
  - cmd: 'cd cpp-libface\libface-project'
  - qmake "CONFIG+=debug" libface.pro
  - nmake.exe
  - cmd: 'copy debug\face.lib ..\..\libs'
  - cmd: 'cd ..\..'
  - if defined XPIKS_BINARY cd xpiks-qt
  - if defined XPIKS_TESTS cd xpiks-tests
  - if defined XPIKS_BINARY qmake "CONFIG+=debug appveyor" xpiks-qt.pro
  - if defined XPIKS_TESTS qmake "CONFIG+=debug appveyor" xpiks-tests.pro
  - nmake.exe

test_script:
  - if defined XPIKS_TESTS debug\xpiks-tests-core.exe
  
